#!/bin/sh	
#	
# /etc/rc.d/avahi: start/stop avahi service	
#	

. /etc/rc.subr

PROG=/usr/sbin/avahi-daemon
	
case $1 in	
	start)	
		msg "Starting avahi-daemon service..."	
		start_daemon /usr/sbin/avahi-daemon -D
		;;	
	stop)	
		msg "Stopping avahi-daemon service..."	
		stop_daemon $PROG
		;;	
	restart)	
		$0 stop	
		sleep 1	
		$0 start	
		;;	
	status)	
		status_daemon $PROG
		;;	
	*)	
		echo "Usage: $0 [start|stop|restart|status]"	
		;;	
esac

# End of file
